# Generated by Django 5.1.5 on 2025-06-04 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('district', '0001_initial'),
        ('facility', '0002_facility_slug_alter_facility_name'),
        ('level', '0001_initial'),
        ('type', '0001_initial'),
        ('university', '0002_university_foreign_affiliated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=210, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/logos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='school/covers/')),
                ('address', models.CharField(max_length=255)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('verification', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('level_text', models.CharField(blank=True, max_length=150)),
                ('website', models.URLField(blank=True, null=True)),
                ('priority', models.PositiveIntegerField(default=999)),
                ('map_link', models.URLField(blank=True, max_length=1024)),
                ('salient_feature', models.TextField(blank=True)),
                ('scholarship', models.TextField(blank=True)),
                ('about_college', models.TextField(blank=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='district.district')),
                ('facilities', models.ManyToManyField(blank=True, related_name='schools', to='facility.facility')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='level.level')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='type.type')),
                ('universities', models.ManyToManyField(blank=True, related_name='schools', to='university.university')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBrochure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='school/brochures/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brochures', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='school/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='school/messages/')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=255)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('admin_open', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_courses', to='course.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_courses', to='school.school')),
            ],
            options={
                'unique_together': {('school', 'course')},
            },
        ),
    ]
