# Generated by Django 5.2.2 on 2025-06-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_school_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolbrochure',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='school/brochures/'),
        ),
        migrations.AlterField(
            model_name='schoolemail',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='schoolfaq',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schoolfaq',
            name='question',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='schoolgallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='school/gallery/'),
        ),
        migrations.AlterField(
            model_name='schoolmessage',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='schoolmessage',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolmessage',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolphone',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolsocialmedia',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='schoolsocialmedia',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
