# Generated by Django 5.2.2 on 2025-06-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_school_address_alter_schoolbrochure_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='school/og/'),
        ),
        migrations.AddField(
            model_name='school',
            name='og_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
