# Generated by Django 5.2.2 on 2025-06-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_school_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
