# Generated by Django 5.2.2 on 2025-06-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_school_admin_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='map_link',
            field=models.URLField(blank=True, max_length=10024),
        ),
    ]
