# Generated by Django 5.1.5 on 2025-06-04 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
        ('university', '0002_university_foreign_affiliated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('event_date', models.DateField()),
                ('event_end_date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(help_text='e.g. 10:00 AM - 5:00 PM', max_length=40)),
                ('organizer_custom', models.CharField(blank=True, help_text='If organizer is not a listed school/university', max_length=120)),
                ('venue', models.CharField(max_length=250)),
                ('event_type', models.CharField(choices=[('online', 'Online'), ('physical', 'Physical'), ('hybrid', 'Hybrid')], max_length=10)),
                ('seat_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=10)),
                ('registration_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='school.school')),
                ('organizer_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='university.university')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
