# Generated by Django 5.2.2 on 2025-06-07 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_long_description'),
        ('inquiry', '0001_initial'),
        ('school', '0007_school_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistrationinquiry',
            name='grade_or_class',
        ),
        migrations.RemoveField(
            model_name='preregistrationinquiry',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='preregistrationinquiry',
            name='student_full_name',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='preregistrationinquiry',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='preregistrationinquiry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_registrations', to='course.course'),
        ),
        migrations.AddField(
            model_name='preregistrationinquiry',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='preregistrationinquiry',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='preregistrationinquiry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='school.school'),
        ),
    ]
