# Generated by Django 5.2.2 on 2025-06-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_remove_preregistrationinquiry_grade_or_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preregistrationinquiry',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preregistrationinquiry',
            name='contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
