# Generated by Django 5.2.2 on 2025-06-07 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_long_description'),
        ('inquiry', '0003_inquiry_contacted_inquiry_contacted_at_and_more'),
        ('school', '0007_school_admin_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='preregistrationinquiry',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='school.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='preregistrationinquiry',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course'),
        ),
        migrations.AlterField(
            model_name='preregistrationinquiry',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
