# Generated by Django 5.1.5 on 2025-06-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('level', '0001_initial'),
        ('school', '0001_initial'),
        ('university', '0002_university_foreign_affiliated'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Information Category',
                'verbose_name_plural': 'Information Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('published_date', models.DateField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='information/images/')),
                ('top_description', models.TextField(blank=True)),
                ('below_description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='information_posts', to='course.course')),
                ('levels', models.ManyToManyField(blank=True, related_name='information_posts', to='level.level')),
                ('schools', models.ManyToManyField(blank=True, related_name='information_posts', to='school.school')),
                ('universities', models.ManyToManyField(blank=True, related_name='information_posts', to='university.university')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='information.informationcategory')),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
