# Generated by Django 5.2.2 on 2025-06-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='information/banners/'),
        ),
        migrations.AddField(
            model_name='information',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='information',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='information',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='informationcategory',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7),
        ),
        migrations.AddField(
            model_name='informationcategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
