# Generated by Django 5.2.2 on 2025-06-06 12:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_long_description'),
        ('information', '0002_information_banner_image_information_content_and_more'),
        ('level', '0001_initial'),
        ('school', '0005_school_meta_description_school_meta_title_and_more'),
        ('university', '0002_university_foreign_affiliated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': 'Information', 'verbose_name_plural': 'Information'},
        ),
        migrations.AddField(
            model_name='informationcategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='informationcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='informationcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_set', to='information.informationcategory'),
        ),
        migrations.AlterField(
            model_name='information',
            name='content',
            field=models.TextField(blank=True, help_text='Main content body'),
        ),
        migrations.AlterField(
            model_name='information',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='information', to='course.course'),
        ),
        migrations.AlterField(
            model_name='information',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='information/featured/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='information', to='level.level'),
        ),
        migrations.AlterField(
            model_name='information',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO description (max 160 chars)', max_length=160),
        ),
        migrations.AlterField(
            model_name='information',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma separated', max_length=255),
        ),
        migrations.AlterField(
            model_name='information',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (max 60 chars)', max_length=60),
        ),
        migrations.AlterField(
            model_name='information',
            name='schools',
            field=models.ManyToManyField(blank=True, related_name='information', to='school.school'),
        ),
        migrations.AlterField(
            model_name='information',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='summary',
            field=models.CharField(blank=True, help_text='Brief summary for listings', max_length=500),
        ),
        migrations.AlterField(
            model_name='information',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='information',
            name='universities',
            field=models.ManyToManyField(blank=True, related_name='information', to='university.university'),
        ),
        migrations.AlterField(
            model_name='informationcategory',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Enter a valid hex color code')]),
        ),
        migrations.AlterField(
            model_name='informationcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
    ]
