# Generated by Django 5.1.5 on 2025-06-04 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('level', '0001_initial'),
        ('school', '0001_initial'),
        ('university', '0002_university_foreign_affiliated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('published_date', models.DateField()),
                ('active_from', models.DateField()),
                ('active_until', models.DateField()),
                ('organizer_custom', models.CharField(blank=True, help_text='Use this if organizer is not a school/university', max_length=255)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='scholarships', to='course.course')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='level.level')),
                ('organizer_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to='school.school')),
                ('organizer_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scholarships', to='university.university')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_scholarships', to='university.university')),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
