# Generated by Django 5.2.2 on 2025-06-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='amount',
            field=models.CharField(blank=True, help_text='e.g., Rs. 50,000 or Full Tuition', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='application_process',
            field=models.TextField(blank=True, help_text='How to apply step by step'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 4 years, 1 semester', max_length=100),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='eligibility_criteria',
            field=models.TextField(blank=True, help_text='Who can apply for this scholarship'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='recipients_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of recipients', null=True),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='required_documents',
            field=models.TextField(blank=True, help_text='List of required documents'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='scholarship_type',
            field=models.CharField(blank=True, choices=[('merit', 'Merit-based'), ('need', 'Need-based'), ('sports', 'Sports'), ('academic', 'Academic Excellence'), ('minority', 'Minority'), ('research', 'Research'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='website_url',
            field=models.URLField(blank=True, help_text='Application or information website'),
        ),
    ]
