# Generated by Django 5.2.2 on 2025-06-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0002_scholarship_additional_notes_scholarship_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='additional_notes',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='application_process',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='eligibility_criteria',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='recipients_count',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='required_documents',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='scholarship_type',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='website_url',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='attachment',
            field=models.FileField(blank=True, help_text='Scholarship brochure or related documents', null=True, upload_to='scholarships/attachments/'),
        ),
        migrations.AddField(
            model_name='scholarship',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description about the scholarship'),
        ),
    ]
