# Generated by Django 5.1.5 on 2025-06-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='foreign_affiliated',
            field=models.BooleanField(default=False),
        ),
    ]
