# Generated by Django 5.2.2 on 2025-06-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_university_foreign_affiliated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterModelOptions(
            name='universitygallery',
            options={'verbose_name': 'University Gallery', 'verbose_name_plural': 'University Galleries'},
        ),
        migrations.AlterField(
            model_name='university',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
